# Default values for aikitoperator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagestream:
  name: s2i-aikit
  version: v0.0.1
  registry:
    name: registry.connect.redhat.com/intel

