# Default values for aikitoperator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

imagestream:
  name: s2i-aikit
  namespace: redhat-ods-applications
  version: v0.0.1
  registry:
    name: quay.io/kamkasravi

