apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "aikit.intel/v1alpha1",
          "kind": "AIKitOperator",
          "metadata": {
            "name": "aikitoperator-sample",
            "namespace": "aikit-operator-system"
          },
          "spec": {
            "fullnameOverride": "",
            "imagestream": {
              "name": "s2i-aikit",
              "namespace": "redhat-ods-applications",
              "registry": {
                "name": "quay.io/kamkasravi"
              },
              "version": "v0.0.1"
            },
            "nameOverride": ""
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.8.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: aikit-operator.v1.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AIKitOperator
      name: aikitoperators.aikit.intel
      version: v1alpha1
  description: AIKit Operator deploys an ImageStream and OdhDocuments to the cluster
    that add aikit notebook image and odh-dashboard cards
  displayName: AIKit Operator
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAABKVBMVEX////z8/MAAAABaLX39/f8/Pz///3//v////sAY7FGgbnt+f/8//8EBAT5//8Cx/7D6vsdZ54AZ69iYmK9vb3Ozs6rq6uDg4MAarOJr9J2dnYsLCw+Pj7g4OCOjo4IY7sAyPyZmZkAY59MTEz///bg//9JyfEAx/wAyfY7x+jLy8u1tbXm+vw1eKqE4PELv/8EteS0+/4WFhba2tpJSUkAab00NDRWVlZsbGxBQUElJSWVlZUcHBxxcXFBeaT//+wA0f/O/f4ndbB4o8AAWJis0edunsOQu9QAWZLa8fxmmb6txd7L8Pi44ftplcQAUo6AnbVMd5Vgh6e57//v/+3/8f8Jb56i4ux46OiG0+9+uNlMx9sAyt9HtdIAzPBQu+YAu9QVsdWq//6M4OQTAAAN6klEQVR4nO2dC2PaRhLHJVkryY0sJwaDDyyCDdSOIE1ibMCOHSep26TX3KPXxz1yba/9/h/iZmYfWoFss6SNcb1/Jw4IIbQ/ZmZnZhVw3EXkO7+H4iSOzrtBkgRR8u710dHRysbK0UqujdVP7sFuQRR88Ev5Cw3bWSJYThiyiCGy7uDzi6OHFtYVCiIWxHGSsCj44sEGGpaFdamCbgSoYsdPvnqwu3p0tGFhXa6gy4BVFCW9Ly9WybAsrCtE8SoafHlxdGRhXaME41U0eLO7QrCmZWHpong1ePN2Q6CaAmZh6WI8Xm1sbXFUlGlZWKQgCEKIU2EYAgCu4Ks/Q2zf2sVwtWJhKcUJwAkhTgGsMOqi4sEXP1ysTCGysCBbdzgsyKzIphjY1/3PH+xurVAyamHprAKoAeMgBP87Pwebupckg69fX4hkwcIqCCCBTYF9ReCBUTLovXvzgDLRlZWtUlJ3GhbQAtPCmAUpw+Avnz/e3cWMYYtmwtkc627DighWnAzeffH1X9/+bRfyhS1gtEFpu4U1Swvc7+/fvNi92MWIvrq6SqgsrBIFFKtevN0lzwMPfLjKWW1ZN5xWHENidW/wGnyPs5JItmyAn1ESUxb6GgxqhWZBNDBRP9s8axpW1HXiYPB49TI7srCUsNiJE4A1PysLy8KysCwsC8vCsrAsLAtrHgGsoCwpLS8L7zqsIIJyp/d49eGR0qq8YWFNwXIAlj94cbGxqrQhtFJeA91dWLFD/ax/vHic6wXX64vyxsPdhQUKcL0+GSS5Bnhn8O1r23WYEV6LFftxoJTQRTT37u/amFVUAKziGANXrAwLNuH9+7u2UzoFK0BYOCXmlhUFSQD3LawZVgEGeVy26ObC5WkLqwwWHzN4nhJeqRx3IwtrWlHAjSuPWBDc8bJusKwHNsDPI4zwyf0HNnW4XqGDEd/CmksWloEsLANZWAaysAxkYRnIwjKQhWUgC8tAFpaBLCwDWVgGsrAMZGEZyMIykIVlIAvLQBaWgSwsA1lYBrKwDGRhGcjCMpCFZSALy0AWloEsLANZWAaysAxkYRnIwjKQhWUgC8tAFpaBLCwDWVgGsrAMZGEZyMIykIVlIAvLQBaWgSwsA1lYBrKwDGRhGcjCMpCFZSALy0AWloEsLANZWAaysAxkYRnIwjKQhWUgC8tAFtZlCsOkGyVxGMXaJrgbxfhhY1uzOtra+GSAO9w9WAHA+q6bhN93k1goDEOG39VwiWUdrWy8eBXj1xl9+KvfMlhJGEbnfvj991G+7RzUjQbf/vD66OGsVjZ2X/SSACh/+KvfLlj4cX8AC34PYiaEXwHCQpbcf/t2t0xv334zAMZxctdgOeh83Xv//Oyzf32m9G/xz3/+dIneDGLkfNdgwZQGxtV7/8tP/93fk3ryZH2vvf/Lj70yHHEygJ8gipy7B6sbwPB7j9rtl3vrutp7T3/shXGJgG4MntoN4usP/8eDFYa9T8GY2vtSL/fb6+t7+49eJSWsnC6kDPhpitH1R/+jwYrAVMLBo3WgpfTyp/39dhthOeGswAHp0xTvnmXhpBZFvff760XttV/uf9oLw2BWEX1CbhDcvQCPsGKEBaYktUew2m2AxaISWpRv4Ico3jVYAcKCmLVXMC0IX+tP2o96v0FBc7VuH6zQwppPFpaBLCwDWVgGsrAMZGEZyMIykM2zDAQZfAyW9R6qwZwV1YlP1qE2tLAKgkIvDAcIq636WWRcbQtrWkF3kCRB71F7fV11aPaxWfPyJXUdfmfdNlj4RQy9R+tP1gvaa68/+bn3W6xJXKnbBouF2CkFvyvAAi98+rO1rKICFoZB3Hv/9On/nk7plx9fDfIdGYO/4qa6lT86u0nbwOinRMx3F8F1c18lgyvSybNnz359VtCvvz57p8d3MVyiMvuyDFiyguiuz8SjUw+qnW6XZdE3yJwzmBK1L1bD5jF+TdF5V6elrMN3SnAV2eFfn0lrYqzUrhxywwV43SwsXJE+z7/Q6bwbhayL69I5LDQDp18FZaxk8Bk9pJRtumSM8gRZtVzDhUzrJmMWLd+H3wVyRcKJyLYYgMx3REJDDzVynVlYFa+og9FhLZVQwRubXql2Fhr3TV4YgjNiGHbz9ZskFv/qsyGMuMVHmJVE62lYpLpLMQ6Zjcph1ditgjWvgFU68ta8tTVvPB+sNc87rYLv0pygLAuev6bBWmg6XHpYMOQMR4ouls7Sqkg+Oiy4u+nwObGpbdRw7bDblDrMD4s5Yw5rDSJNOazKcJM03KzujDmYEwQLz5UPZE0k1RoO+d30VgX4+WE56QGMc5t+XeKGDQ2iP+RhqqHlHCB3hMRrcot7A26oEhr+o86NqVlePcJ4DCmm3HlCJPedzdFZDa2q2sTBDi+DpZ2J4x6iEa2lPMhLhoSwppAuNOwPgiXzYTwtH0Oxhoizw7iRM2CMFWd/JqsZfsNnJeUJw2GOnDrCalwKSxfPNGqFQ/nNJYClGQbPnyUERVN3Wf29VvTyI5TCGnL/IQKjdA5YzKcgNykcaQlgwVBqO/XJZPK8lvHqTdW8eDq+L8BltdZk0tipulMlCN3e7MMhzuo71dQpyTqdMwzYqYMEPK8/BywHHRdCfCGw3jwstwZxV2rU0GZ25tRPTponzWMYpV9tyin7pOY6Rctya4dqPj+YDGervxRHeQZvQg3NZXsOWFAd0eHcpXLDalOmODwP8uoqigMsDmDCWENPhCoaDDCjbCRTRr7Hcz2u0W8aeB+x0lHSqahXZllOlXZ1l8ayIKmbqHEKgeUM1awoYB2m5D4SJ9DS4pzf4A9QtkhJujfxcxp0q4mP0O4VvNWaaiWUxSyE5S0XrIkwF8JEQ0Y3GfI6Q8HqNLjVrMmdZdiBwO+3xJM9fgjQAeZHfj6nOqnMmQSCY7eYXZRaVp8sa4liVsubEjeuUzkYAeu0UJIhrEM+CLCgHU/DqHwxL5cRFr1MRnfdbdw3cwrzaymsHYS1vTywqioQjSb1542OolUvuiHtVam36ofyjhg6o5KP8DTrWZpWK+Lxju4+VEN3XO61dTpWkUvpbDgS5rgssLY94XgNGptf5UNdU9VuXaEaER0enxCOOGNWEc8YpzwBey7obqqeO7reGsYpLsq4DoqpVjGD5xlulQ67NEkpWIVwm+fixUXaDJrwLQrWiRid3xHwGtrQ4X5TpPHMETPGmRbh6TniAMw/5PlpCSw1a2CT4gB3O3HZksBidRFqjmUy4zMZxE583Q21wT3nc543ljS5oVVFPSQnMSht1Ciphh6reE+x6LAQiwhWXYPi1g7oVVrOklgWSztTJGAA6amglemWBe+wPMGqBCwNjSbCY1ctwvhiTnCLdHJ/InbgptOwxn2h2k7rgFt8p5j93hws35c+dzDMV16YbFrWCrAqqgTKhN/xLHx4wmFNHDgeyvVdcdA8aGFkPFHDxs7WdDivqIlGCVmN0qklwxt0w01xXs1CgSOsreXos2HuDps8OxWwMo9nDaPKGH7wT0XQXsvyZ8DuFS2EVWnCSDUPE53SKV6dmYL75mD5fXFSqlRj3GdIE302lDMAH7r2pGrpKGmbsqwGstF7WJBqeVT8KFolluVtF+eAG4Xlu0xyOdSjaE1Y1rgAa+cKWLLSKUr5NiVZXmes6QS3HE/B8tYOhE5PR53GZqHOWUZYTMLyTGCVoMJ1CZGj92eNhkckzckKPfjN4ZCvsc52epbJDTGulLthvsgwDYuXOqPOtMZyrCMR5GQR6okKklIFpsHSk3Vt9X4ZYMG8lYlxj+RUh2fYEkOqz2VZmagF6yXnxJWqxs2UbVE1rVtWsbIp1Q1alkodUpkS+VTPePkZXQdreMoHXimuwmgNa+xJeJVWUQ16WqZmyNJCeplg+W66Ld7jft5sT08EjOpcsNxDCkBek2Y7VQ3mZaFLSdbMeg711yvFAL/EsOCFWEPAmuSDk3Hs1C3kWZfBcs44LGyOSmdmshlGTVTqMcz4F/XX87XpZYeFz1JZkmzl5dVOxZkPVia7EFmeCcBhFHxqjFanW/Kiu6yOegtg+Y5g5Z1wp3PSsYy/2XywGLkZ9Qtras3WrY+h+CFnTA+4lc6Mmmr4Y/mUK2Fpl0kWF1mZ/1GX72ueaCZ7lVqWVfPu1UTEnWth+RnvJsOWZqufZVm/hmGsJVYPyd3qJdMcN2oZy66GxQqwtJr841qWXxGdUTm5yzWL1Cm0aC53Q8bOPNm+99RB8AB00Sd1F7OS8ftNfW36GljOMOUa0rUOLXlvoetvF+/B4+QnckSxfEO3a1MLFpfCwuuuOnJtRzCnWw0yB6qhm6XjJz+Ua9NXwoLXOM3fCL0c2HEXccSFV3dYeuh5ml3xk+k7/pxuSNlBR3buPbXG453SVY5nuOl5yZUPdNFk3py+Jmbp12fpxdXHvfIPxpNOPNk2EKn2diavAWHl5Q5v96mROG5dkhaWhQ0YWgEb8cA0U7ogYkq1jvljNGc2VM9sRvllkoVioLZQhF8cFvaBz/QTaPb1VFzm8y21TdZIJ/pbv1nXD+Ed9/nlEVSUT/zZihhTMV6Epo5qB04uK3eYc+CVamehYX8ALIxObm0yPtwebXcqraGbFy5odxn1AbJ83cCHLfhHb8zBYdx+vdLZHo2Ox5WdoTwAPXtY2j4Ae8w2s2HGZ5Ih7qh3A6f2zTbLlKUf17LyixLcNHW560H6ktfVui2IG2XDoT19eYzCZQ5OmWXlm3ymlUml1yJe/p8GFku0/g8T0BTQLxFmNAAAAABJRU5ErkJggg=="
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - aikit.intel
          resources:
          - aikitoperators
          - aikitoperators/status
          - aikitoperators/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: aikit-operator-controller-manager
      deployments:
      - name: aikit-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                - --leader-election-id=aikit-operator
                image: quay.io/kamkasravi/aikit-operator:1.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 90Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: aikit-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: aikit-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - aikit
  - deeplearning
  - machinelearning
  links:
  - name: Aikit Operator
    url: https://aikit-operator.domain
  maturity: alpha
  provider:
    name: Intel
  version: 1.0.1
