apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: {{ .Values.imagestream.name }}
  namespace: {{ .Values.imagestream.namespace }}
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-python-dependencies: {{ .Values.imagestream.notebook-python-dependencies }}
      opendatahub.io/notebook-software: {{ .Values.imagestream.notebook-software }}
  - name: {{ .Values.imagestream.name }}
    from:
      kind: DockerImage
      name: {{ .Values.imagestream.registry.root }}/{{ .Values.imagestream.registry.repo }}/{{ .Values.imagestream.registry.name }}:{{ .Values.imagestream.registry.version }}
    referencePolicy:
      type: Source
