apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "oneAPI AI Analytics Toolkit"
  labels:
    opendatahub.io/notebook-image: "true"
  name: {{ .Values.imagestream.name }}
  namespace: {{ .Values.imagestream.namespace }}
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.imagestream.name }}
    annotations:
      opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.4.4"},{"name":"Notebook","version":"7.2.2"}]'
      opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}, {"name":"AiKit","version":"2022.3.0"}]'
    from:
      kind: DockerImage
      name: {{ .Values.imagestream.registry.root }}/{{ .Values.imagestream.registry.repo }}/{{ .Values.imagestream.registry.name }}:{{ .Values.imagestream.registry.version }}
    referencePolicy:
      type: Source
