apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: {{ .Values.imagestream.name }}
  namespace: {{ .Values.imagestream.namespace }}
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.imagestream.version }}
    from:
      kind: DockerImage
      name: {{ .Values.imagestream.registry.root }}/{{ .Values.imagestream.registry.repo }}/{{ .Values.imagestream.registry.name }}:{{ .Values.imagestream.registry.version }}
    referencePolicy:
      type: Source
