apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: aikit-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: AIKit Operator deploys an ImageStream and OdhDocuments to the cluster
    that add aikit notebook image and odh-dashboard cards
  displayName: AIKit Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - aikit
  - deeplearning
  - machinelearning
  links:
  - name: Aikit Operator
    url: https://aikit-operator.domain
  maturity: alpha
  provider:
    name: Intel
  version: 0.0.0
