apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: {{ .Values.imagestream.name }}
spec:
  lookupPolicy:
    local: true
  tags:
    from:
      kind: DockerImage
      name: {{ .Values.imagestream.name }}/{{ .Values.imagestream.name }}:{{ .Values.imagestream.version }}
    importPolicy: {}
    name: {{ .Values.imagestream.version }}
    referencePolicy:
      type: Source
