apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-lab-elyra
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/thoth-station/s2i-lab-elyra
    from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-lab-elyra:v0.0.6
    importPolicy: {}
    name: v0.0.6
    referencePolicy:
      type: Source
